"use client";
import {ChangeEvent,DragEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
type Color={id:string,name:string,hex:string}; type Cell=Color|null;
const P:Color[]=[
 ["01","하늘","#8FD0EB"],["02","연두","#93C94B"],["03","검정","#202124"],["04","분홍","#F36E9A"],["05","초록","#2E9B5F"],["06","주황","#F47B20"],["07","노랑","#F8C928"],["08","흰색","#F7F7F2"],
 ["09","빨강","#E53935"],["10","파랑","#2475C8"],["11","보라","#8246A8"],["12","갈색","#755035"],["13","회색","#777B80"],["14","연회색","#BFC3C6"],["15","살구","#F4B985"],["16","아이보리","#F4E6C7"],
 ["17","진초록","#176B45"],["18","진파랑","#174C8E"],["19","진노랑","#F3A712"],["20","진분홍","#D93D75"],["21","연분홍","#F5B2C4"],["22","민트","#56BFC1"],["23","연보라","#B99AD9"],["24","연파랑","#AFD8EC"],
 ["25","다크브라운","#4D2D1C"],["26","베이지","#D7B78B"],["27","형광연두","#B6DB46"],["28","청록","#178F93"],["29","자주","#9B315F"],["30","코랄","#F08A72"],["31","남색","#293B67"],["32","다크옐로우","#C58A27"]
].map(([id,name,hex])=>({id,name,hex}));
const RGB=(h:string)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
const dist=(a:number[],b:number[])=>.9*(a[0]-b[0])**2+1.4*(a[1]-b[1])**2+.7*(a[2]-b[2])**2;
const clamp=(n:number,a=8,b=160)=>Math.max(a,Math.min(b,Math.round(n||a)));
export default function Home(){
 const [img,setImg]=useState<HTMLImageElement|null>(null),[name,setName]=useState(""),[cols,setCols]=useState(48),[rows,setRows]=useState(48),[limit,setLimit]=useState(16),[mode,setMode]=useState<"cover"|"contain">("cover"),[blank,setBlank]=useState(false),[cells,setCells]=useState<Cell[]>([]),[zoom,setZoom]=useState(100),[drag,setDrag]=useState(false);
 const input=useRef<HTMLInputElement>(null),canvas=useRef<HTMLCanvasElement>(null);
 const load=useCallback((f?:File)=>{if(!f||!f.type.startsWith("image/"))return;if(f.size>15*1024*1024)return alert("15MB 이하 이미지를 선택해주세요.");const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{setImg(i);setName(f.name);URL.revokeObjectURL(u)};i.src=u},[]);
 const sample=useCallback(()=>{const c=document.createElement("canvas"),x=c.getContext("2d")!;c.width=c.height=640;let g=x.createLinearGradient(0,0,640,640);g.addColorStop(0,"#d8f2ff");g.addColorStop(1,"#fff4d8");x.fillStyle=g;x.fillRect(0,0,640,640);x.fillStyle="#f48b20";x.beginPath();x.arc(320,330,210,0,7);x.fill();x.fillStyle="#5b351f";x.beginPath();x.moveTo(145,230);x.lineTo(190,65);x.lineTo(300,190);x.fill();x.beginPath();x.moveTo(495,230);x.lineTo(450,65);x.lineTo(340,190);x.fill();x.fillStyle="#fff1d6";x.beginPath();x.ellipse(320,410,145,120,0,0,7);x.fill();x.fillStyle="#222";x.beginPath();x.arc(245,325,24,0,7);x.arc(395,325,24,0,7);x.fill();x.fillStyle="#e96f5d";x.beginPath();x.moveTo(320,400);x.lineTo(292,372);x.lineTo(348,372);x.fill();const i=new Image();i.onload=()=>{setImg(i);setName("예시_여우.png")};i.src=c.toDataURL()},[]);
 const generate=useCallback(()=>{if(!img){sample();return}const c=document.createElement("canvas"),x=c.getContext("2d",{willReadFrequently:true})!;c.width=cols;c.height=rows;x.fillStyle="#fff";x.fillRect(0,0,cols,rows);const s=mode==="cover"?Math.max(cols/img.width,rows/img.height):Math.min(cols/img.width,rows/img.height),w=img.width*s,h=img.height*s;x.drawImage(img,(cols-w)/2,(rows-h)/2,w,h);const d=x.getImageData(0,0,cols,rows).data,raw:{p:number[],c:Color}[]=[],count=new Map<string,number>();for(let n=0;n<d.length;n+=4){let p=[d[n],d[n+1],d[n+2]],best=P[0],bd=Infinity;P.forEach(c=>{let q=dist(p,RGB(c.hex));if(q<bd){bd=q;best=c}});raw.push({p,c:best});count.set(best.id,(count.get(best.id)||0)+1)}const use=[...P].sort((a,b)=>(count.get(b.id)||0)-(count.get(a.id)||0)).slice(0,limit);setCells(raw.map(({p})=>{if(blank&&p.every(v=>v>242))return null;let best=use[0],bd=Infinity;use.forEach(c=>{let q=dist(p,RGB(c.hex));if(q<bd){bd=q;best=c}});return best}))},[img,cols,rows,mode,limit,blank,sample]);
 useEffect(()=>{if(img){const t=setTimeout(generate,160);return()=>clearTimeout(t)}},[img,cols,rows,mode,limit,blank,generate]);
 useEffect(()=>{if(!cells.length||!canvas.current)return;const z=18,c=canvas.current,x=c.getContext("2d")!;c.width=cols*z;c.height=rows*z;cells.forEach((v,n)=>{let a=n%cols*z,b=Math.floor(n/cols)*z;x.fillStyle=v?.hex||"#fff";x.fillRect(a,b,z,z);x.strokeStyle="rgba(24,32,42,.18)";x.strokeRect(a+.5,b+.5,z-1,z-1);if(v){x.beginPath();x.arc(a+9,b+9,4.5,0,7);x.fillStyle="rgba(255,255,255,.2)";x.fill();x.strokeStyle="rgba(0,0,0,.12)";x.stroke()}})},[cells,cols,rows]);
 const summary=useMemo(()=>{const m=new Map<string,{c:Color,n:number}>();cells.forEach(c=>{if(c)m.set(c.id,{c,n:(m.get(c.id)?.n||0)+1})});return[...m.values()].sort((a,b)=>b.n-a.n)},[cells]),total=summary.reduce((s,v)=>s+v.n,0);
 const save=()=>{if(!canvas.current)return;const a=document.createElement("a");a.download=`디폼블럭_${cols}x${rows}.png`;a.href=canvas.current.toDataURL();a.click()};
 const resolution=(v:number,set:(v:number)=>void,d:number)=>set(clamp(v+d));
 return <main><header><div className="brand"><span className="logo">▦</span>디폼블럭 도안 만들기</div><div className="private"><i/>이미지는 기기 안에서만 처리됩니다</div></header><div className="workspace"><aside>
  <section><h2>이미지</h2><input ref={input} hidden type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>load(e.target.files?.[0])}/><button className={`drop ${drag?"on":""}`} onClick={()=>input.current?.click()} onDragOver={(e:DragEvent)=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={(e:DragEvent)=>{e.preventDefault();setDrag(false);load(e.dataTransfer.files[0])}}><b className="up">⇧</b><strong>{name||"이미지를 올려주세요"}</strong><span>{name?"다른 이미지로 바꾸기":"클릭하거나 여기로 끌어놓기"}</span><small>JPG, PNG, WEBP · 최대 15MB</small></button>{!img&&<button className="example" onClick={sample}>예시 이미지로 해보기 →</button>}</section>
  <section><div className="title"><h2>판매 색상표</h2><em>8mm · 32색</em></div><div className="swatches">{P.map(c=><i key={c.id} style={{background:c.hex}} title={`${c.id}. ${c.name}`}/>)}</div><p className="note">국내 판매처의 색상별 구매 목록을 바탕으로 구성했습니다. 화면 색상은 실제 블록과 조금 다를 수 있습니다.</p><label className="range-label">사용할 최대 색상 <b>{limit}색</b></label><input className="range" type="range" min="4" max="32" value={limit} onChange={e=>setLimit(+e.target.value)}/></section>
  <section><div className="title"><h2>해상도</h2><span>완성 크기 약 {(cols*.8).toFixed(1)} × {(rows*.8).toFixed(1)}cm</span></div><div className="res"><label>가로<div className="step"><button onClick={()=>resolution(cols,setCols,-1)}>−</button><input value={cols} onChange={e=>setCols(clamp(+e.target.value))}/><button onClick={()=>resolution(cols,setCols,1)}>＋</button></div></label><b>×</b><label>세로<div className="step"><button onClick={()=>resolution(rows,setRows,-1)}>−</button><input value={rows} onChange={e=>setRows(clamp(+e.target.value))}/><button onClick={()=>resolution(rows,setRows,1)}>＋</button></div></label></div><div className="presets">{[[32,32],[48,48],[64,64],[80,60]].map(([w,h])=><button key={w+"x"+h} onClick={()=>{setCols(w);setRows(h)}}>{w}×{h}</button>)}</div><div className="fit"><button className={mode==="cover"?"active":""} onClick={()=>setMode("cover")}>빈틈없이 채우기</button><button className={mode==="contain"?"active":""} onClick={()=>setMode("contain")}>전체 이미지 맞추기</button></div><label className="check"><input type="checkbox" checked={blank} onChange={e=>setBlank(e.target.checked)}/>흰색 배경은 블록 없이 비우기</label></section>
  <button className="generate" onClick={generate}>{img?"도안 다시 만들기":"예시 도안 만들기"} →</button>
 </aside><article><div className="preview-title"><div><h1>도안 미리보기</h1><p>{cells.length?`${cols} × ${rows}칸 · ${total.toLocaleString()}개 블록`:"이미지를 올리면 도안이 여기에 표시됩니다"}</p></div><div><button disabled={!cells.length} onClick={()=>print()}>인쇄</button><button className="save" disabled={!cells.length} onClick={save}>PNG 저장</button></div></div><div className="stage">{cells.length?<div className="scroll"><canvas ref={canvas} style={{width:`${zoom}%`}}/></div>:<div className="empty"><span>▦</span><strong>나만의 블록 도안을 만들어보세요</strong><p>사진이나 그림을 올리고 원하는 가로·세로 칸 수를 입력하세요.</p><button onClick={()=>input.current?.click()}>이미지 선택</button></div>}{cells.length>0&&<div className="zoom"><button onClick={()=>setZoom(Math.min(240,zoom+10))}>＋</button><small>{zoom}%</small><button onClick={()=>setZoom(Math.max(40,zoom-10))}>−</button></div>}</div><div className="summary"><div className="summary-head"><h2>필요한 블록</h2><span>총 <b>{total.toLocaleString()}</b>개 · {summary.length}색</span></div>{summary.length?<div className="colors">{summary.map(({c,n})=><div className="color" key={c.id}><i style={{background:c.hex}}/><p><b>{c.id}. {c.name}</b><small>{n.toLocaleString()}개</small></p></div>)}</div>:<p className="none">도안을 만들면 색상별 필요 수량을 계산해드려요.</p>}</div></article></div><footer><span>브라우저에서 직접 변환하므로 이미지가 서버로 전송되지 않습니다.</span><a href="https://www.allcrart.com/m/product.html?branduid=71860" target="_blank" rel="noreferrer">참고한 판매 색상표 ↗</a></footer></main>
}
